Modifications to support updated west_tools. bin/wemd now prefers scripts found in lib/west_tools to those in lib/cmds; bin/wemd lib/cmds/SCRIPTNAME.py can still be used for the old tools. Also added links for west_tools scripts w_bins, w_pdist, w_select.

diff --git a/bin/west b/bin/west
--- a/bin/west
+++ b/bin/west
@@ -47,21 +47,31 @@ if [ "$SCRIPT" == "west" ] ; then
     exec $WEST_PYTHON "$@"
 fi
 
+# Find where the requested script is stashed
+if [ -e "$WEST_ROOT/lib/west_tools/${SCRIPT}.py" ] ; then
+    FULLSCRIPT="$WEST_ROOT/lib/west_tools/${SCRIPT}.py"
+elif [ -e "$WEST_ROOT/lib/cmds/${SCRIPT}.py" ] ; then
+    FULLSCRIPT="$WEST_ROOT/lib/cmds/${SCRIPT}.py"
+else
+    echo "script ${SCRIPT}.py not found"
+    exit 1
+fi
+
 if [ "$1" == "--profile" ]; then
     shift
     pfile=west_profile_$$.dat
     echo >&2 "Saving profiling information to $pfile"
-    $WEST_PYTHON -m cProfile -o $pfile $WEST_ROOT/lib/cmds/${SCRIPT}.py "$@"
+    $WEST_PYTHON -m cProfile -o $pfile $FULLSCRIPT "$@"
     $WEST_PYTHON -c "import sys, pstats; ps = pstats.Stats('$pfile', stream=sys.stderr); ps.sort_stats('time').print_stats(100);"
 elif [ "$1" == "--lprofile" ]; then
     shift
     pfile=west_lprofile_$$.dat
     echo >&2 "Saving line_profiler information to $pfile"
-    $WEST_KERNPROF -l -o $pfile -v $WEST_ROOT/lib/cmds/${SCRIPT}.py "$@"
+    $WEST_KERNPROF -l -o $pfile -v $FULLSCRIPT "$@"
 elif [ "$1" == "--strace" ]; then
     shift
     echo >&2 "Running $SCRIPT under strace"
-    strace $WEST_PYTHON $WEST_ROOT/lib/cmds/${SCRIPT}.py "$@"
+    strace $WEST_PYTHON $FULLSCRIPT "$@"
 else
-    exec $WEST_PYTHON $WEST_ROOT/lib/cmds/${SCRIPT}.py "$@"
+    exec $WEST_PYTHON $FULLSCRIPT "$@"
 fi
